# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThreeMonths' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'Alamofire', '4.9.1'
  pod 'SwiftyJSON'
  pod 'HandyJSON'
  pod 'MJRefresh' 
  pod 'SDWebImage'
 # pod 'RxSwift', '5.0.1'
 # pod 'RxCocoa'	


  # Pods for ThreeMonths

  target 'ThreeMonthsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThreeMonthsUITests' do
    # Pods for testing
     
  end

end
